# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rushcheck}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daisuke IKEGAMI"]
  s.date = %q{2011-03-28}
  s.description = %q{Specification based random testing framework like QuickCheck in Haskell}
  s.email = %q{ikegami.da@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "data/doc/policy.txt",
    "data/doc/rushcheck.thtml",
    "data/doc/spec.txt",
    "data/examples/candy.rb",
    "data/examples/printf.rb",
    "data/examples/proc.rb",
    "data/examples/roguetile.rb",
    "data/examples/rspec/stack.rb",
    "data/examples/rspec/stack_spec.rb",
    "data/examples/sample.rb",
    "lib/rushcheck.rb",
    "lib/rushcheck/arbitrary.rb",
    "lib/rushcheck/array.rb",
    "lib/rushcheck/assertion.rb",
    "lib/rushcheck/bool.rb",
#   "lib/rushcheck/claim.rb",
    "lib/rushcheck/config.rb",
    "lib/rushcheck/float.rb",
    "lib/rushcheck/gen.rb",
    "lib/rushcheck/guard.rb",
    "lib/rushcheck/hash.rb",
    "lib/rushcheck/integer.rb",
    "lib/rushcheck/proc.rb",
    "lib/rushcheck/property.rb",
    "lib/rushcheck/random.rb",
    "lib/rushcheck/result.rb",
    "lib/rushcheck/string.rb",
    "lib/rushcheck/testable.rb",
    "lib/rushcheck/testoptions.rb",
    "lib/rushcheck/testresult.rb",
    "lib/rushcheck/version.rb",
    "test/helper.rb",
    "test/prelude.rb",
    "test/spec_array.rb",
    "test/spec_assertion.rb",
    "test/spec_gen.rb",
    "test/spec_random.rb",
    "test/test_arbitrary.rb",
    "test/test_array.rb",
    "test/test_assertion.rb",
    "test/test_rushcheck.rb"
  ]
  s.homepage = %q{http://github.com/IKEGAMIDaisuke/rushcheck}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Random testing framework for Ruby}
  s.test_files = [
    "test/helper.rb",
    "test/prelude.rb",
    "test/spec_array.rb",
    "test/spec_assertion.rb",
    "test/spec_gen.rb",
    "test/spec_random.rb",
    "test/test_arbitrary.rb",
    "test/test_array.rb",
    "test/test_assertion.rb",
    "test/test_rushcheck.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

